name: C:\Users\VICTUS\Desktop\pattern project\env
channels:
  - conda-forge
  - nvidia
  - defaults
dependencies:
  - _openmp_mutex=4.5=2_gnu
  - asttokens=3.0.0=pyhd8ed1ab_1
  - brotli=1.1.0=hfd05255_4
  - brotli-bin=1.1.0=hfd05255_4
  - bzip2=1.0.8=h0ad9c76_8
  - ca-certificates=2025.10.5=h4c7d964_0
  - cairo=1.18.4=h5782bbf_0
  - colorama=0.4.6=pyhd8ed1ab_1
  - comm=0.2.3=pyhe01879c_0
  - contourpy=1.3.2=py310hc19bc0b_0
  - cpython=3.10.18=py310hd8ed1ab_0
  - cudatoolkit=11.2.2=h7d7167e_13
  - cudnn=8.1.0.77=h3e0f4f4_0
  - cycler=0.12.1=pyhd8ed1ab_1
  - debugpy=1.8.17=py310h699e580_0
  - decorator=5.2.1=pyhd8ed1ab_0
  - double-conversion=3.3.1=he0c23c2_0
  - exceptiongroup=1.3.0=pyhd8ed1ab_0
  - executing=2.2.1=pyhd8ed1ab_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.15.0=h765892d_1
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - fonttools=4.60.1=py310hdb0e946_0
  - freetype=2.14.1=h57928b3_0
  - graphite2=1.3.14=hac47afa_2
  - harfbuzz=12.1.0=h5f2951f_0
  - icu=75.1=he0c23c2_0
  - importlib-metadata=8.7.0=pyhe01879c_1
  - ipykernel=6.30.1=pyh3521513_0
  - ipython=8.37.0=pyha7b4d00_0
  - jedi=0.19.2=pyhd8ed1ab_1
  - joblib=1.5.2=pyhd8ed1ab_0
  - jupyter_client=8.6.3=pyhd8ed1ab_1
  - jupyter_core=5.8.1=pyh5737063_0
  - kiwisolver=1.4.9=py310h1e1005b_1
  - krb5=1.21.3=hdf4eb48_0
  - lcms2=2.17=hbcf6048_0
  - lerc=4.0.0=h6470a55_1
  - libblas=3.9.0=35_h5709861_mkl
  - libbrotlicommon=1.1.0=hfd05255_4
  - libbrotlidec=1.1.0=hfd05255_4
  - libbrotlienc=1.1.0=hfd05255_4
  - libcblas=3.9.0=35_h2a3cdd5_mkl
  - libclang13=21.1.2=default_ha2db4b5_2
  - libdeflate=1.24=h76ddb4d_0
  - libexpat=2.7.1=hac47afa_0
  - libffi=3.4.6=h537db12_1
  - libfreetype=2.14.1=h57928b3_0
  - libfreetype6=2.14.1=hdbac1cb_0
  - libgcc=15.2.0=h1383e82_6
  - libglib=2.86.0=h5f26cbf_0
  - libgomp=15.2.0=h1383e82_6
  - libhwloc=2.12.1=default_h64bd3f2_1002
  - libiconv=1.18=hc1393d2_2
  - libintl=0.22.5=h5728263_3
  - libjpeg-turbo=3.1.0=h2466b09_0
  - liblapack=3.9.0=35_hf9ab0e9_mkl
  - liblzma=5.8.1=h2466b09_2
  - libpng=1.6.50=h7351971_1
  - libsodium=1.0.20=hc70643c_0
  - libsqlite=3.50.4=hf5d6505_0
  - libtiff=4.7.1=h550210a_0
  - libvulkan-loader=1.4.328.0=h477610d_0
  - libwebp-base=1.6.0=h4d5522a_0
  - libwinpthread=12.0.0.r4.gg4f2fc60ca=h57928b3_10
  - libxcb=1.17.0=h0e4246c_0
  - libxml2=2.15.0=ha29bfb0_1
  - libxml2-16=2.15.0=h06f855e_1
  - libxslt=1.1.43=h0fbe4c1_1
  - libzlib=1.3.1=h2466b09_2
  - llvm-openmp=21.1.2=hfa2b4ca_3
  - matplotlib=3.10.6=py310h5588dad_1
  - matplotlib-base=3.10.6=py310h0bdd906_1
  - matplotlib-inline=0.1.7=pyhd8ed1ab_1
  - mkl=2024.2.2=h57928b3_16
  - munkres=1.1.4=pyhd8ed1ab_1
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - openjpeg=2.5.4=h24db6dd_0
  - openssl=3.5.4=h725018a_0
  - packaging=25.0=pyh29332c3_1
  - pandas=2.3.3=py310hed136d8_1
  - parso=0.8.5=pyhcf101f3_0
  - patsy=1.0.1=pyhd8ed1ab_1
  - pcre2=10.46=h3402e2f_0
  - pickleshare=0.7.5=pyhd8ed1ab_1004
  - pillow=11.3.0=py310hb3a2f59_3
  - pip=25.2=pyh8b19718_0
  - pixman=0.46.4=h5112557_1
  - platformdirs=4.4.0=pyhcf101f3_0
  - prompt-toolkit=3.0.52=pyha770c72_0
  - psutil=7.1.0=py310h29418f3_0
  - pthread-stubs=0.4=h0e40799_1002
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - pygments=2.19.2=pyhd8ed1ab_0
  - pyparsing=3.2.5=pyhcf101f3_0
  - pyside6=6.9.3=py310h96c60bd_1
  - python=3.10.18=h8c5b53a_0_cpython
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-tzdata=2025.2=pyhd8ed1ab_0
  - python_abi=3.10=8_cp310
  - pytz=2025.2=pyhd8ed1ab_0
  - pywin32=311=py310h282bd7d_1
  - pyzmq=27.1.0=py310h535538e_0
  - qhull=2020.2=hc790b64_5
  - qt6-main=6.9.3=ha0de62e_0
  - scikit-learn=1.3.2=py310hfd2573f_2
  - scipy=1.15.2=py310h15c175c_0
  - seaborn=0.12.2=hd8ed1ab_0
  - seaborn-base=0.12.2=pyhd8ed1ab_0
  - setuptools=80.9.0=pyhff2d567_0
  - six=1.17.0=pyhe01879c_1
  - stack_data=0.6.3=pyhd8ed1ab_1
  - statsmodels=0.14.5=py310h8f3aa81_1
  - tbb=2021.13.0=h18a62a1_3
  - threadpoolctl=3.6.0=pyhecae5ae_0
  - tk=8.6.13=h2c6b04d_2
  - tornado=6.5.2=py310h29418f3_1
  - traitlets=5.14.3=pyhd8ed1ab_1
  - typing_extensions=4.15.0=pyhcf101f3_0
  - tzdata=2025b=h78e105d_0
  - ucrt=10.0.26100.0=h57928b3_0
  - unicodedata2=16.0.0=py310h29418f3_1
  - vc=14.3=h41ae7f8_31
  - vc14_runtime=14.44.35208=h818238b_31
  - vcomp14=14.44.35208=h818238b_31
  - vs2015_runtime=14.44.35208=h38c0c73_31
  - wcwidth=0.2.14=pyhd8ed1ab_0
  - wheel=0.45.1=pyhd8ed1ab_1
  - xorg-libxau=1.0.12=h0e40799_0
  - xorg-libxdmcp=1.1.5=h0e40799_0
  - zeromq=4.3.5=h5bddc39_9
  - zipp=3.23.0=pyhd8ed1ab_0
  - zstd=1.5.7=hbeecb71_2
  - pip:
      - absl-py==2.3.1
      - astunparse==1.6.3
      - cachetools==6.2.0
      - certifi==2025.10.5
      - charset-normalizer==3.4.3
      - flatbuffers==25.9.23
      - gast==0.4.0
      - google-auth==2.41.1
      - google-auth-oauthlib==0.4.6
      - google-pasta==0.2.0
      - grpcio==1.75.1
      - h5py==3.14.0
      - idna==3.10
      - keras==2.10.0
      - keras-preprocessing==1.1.2
      - libclang==18.1.1
      - markdown==3.9
      - markupsafe==3.0.3
      - numpy==1.23.5
      - oauthlib==3.3.1
      - opt-einsum==3.4.0
      - protobuf==3.19.6
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.2
      - requests==2.32.5
      - requests-oauthlib==2.0.0
      - rsa==4.9.1
      - tensorboard==2.10.1
      - tensorboard-data-server==0.6.1
      - tensorboard-plugin-wit==1.8.1
      - tensorflow==2.10.0
      - tensorflow-estimator==2.10.0
      - tensorflow-io-gcs-filesystem==0.31.0
      - termcolor==3.1.0
      - urllib3==2.5.0
      - werkzeug==3.1.3
      - wrapt==1.17.3
prefix: C:\Users\VICTUS\Desktop\pattern project\env
