name: C:\Users\VICTUS\Desktop\pattern project\env
channels:
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - ipykernel
  - cudatoolkit=11.2
  - cudnn=8.1.0
  - pandas
  - matplotlib
  - scikit-learn=1.3.2
  - seaborn=0.12.2
prefix: C:\Users\VICTUS\Desktop\pattern project\env
