name: pattern-project
channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.10
  - numpy=1.23
  - pandas
  - scipy
  - scikit-learn=1.3
  - seaborn
  - matplotlib
  - statsmodels
  - jupyter
  - ipykernel
  - tensorflow-gpu=2.19
  - pip
  - pip:
      - visualkeras==0.2.0
      - pydot==4.0.1
